---
title: "Density_dependence"
output: html_document
---

```{r}
#package 
library(ggplot2)
library(tidyverse)
library(stringr)
library(tidyr)
library(scales)
library(colorspace)
library(ggplot2)
library(ggthemes)
library(vegan)
library(ggpmisc)
```

```{r}
#import data haplotype / species 
data_species <- read.csv("Data/Haplotype_data.csv")

#import data sizes for each samples
data_sizes <- read.csv("Data/POC_RA_Size.csv")

#import quadrats benthics cover data
data_quadrats <- read.csv("Data/20260226_Quadrat_Benthos_RA.csv")

```

```{r}
#create new data set with filtering 
#create a selection with the smallest colonies and the biggest colonies 
#small colonies need to be under or equal 5cm square are count as juvenile more than 5cm square is count as adult colonies 
#create data with the corals having a size under 5cm square and a file with the colonies having a size bigger than 5cm square
#create a file with all the species ID and sample number 
#remove all the NA or line who don't have measurement 

#for the small colonie used data sizes and creat both dataset
#removing the column I don't need
data_size_meandiameters <- data_sizes %>%
  select(-Diameter.1, -Diameter.2, -Diameter.3)

str(data_size_meandiameters)

#convert to character 
data_size_meandiameters$Diameter.mean <- as.numeric(data_size_meandiameters$Diameter.mean)

#filter data data_size_meandiameters with juvenille and adult colonies 
juvenile <- data_size_meandiameters %>%
  filter(Diameter.mean <= 4)

adult <- data_size_meandiameters %>%
  filter(Diameter.mean > 4)

```

```{r}
#calculating the density of poc per site in fonction of their sizes 
#juvenille 
density_juvenile <- juvenile %>%
  group_by(Site) %>%
  summarise(count = n()) %>%
  mutate(juvenile.density = count / 75)


#adults 
density_adult <- adult %>%
  group_by(Site) %>%
  summarise(count = n()) %>%
  mutate(adult.density = count / 75)

#combine both density  dataset
density_combine <- left_join(density_juvenile, density_adult, by = "Site")

```

```{r}
#check first with Poc spp.
#plot with ggplot 
ggplot(density_combine, aes(x = adult.density, y = juvenile.density)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Adult density (colonies/m²)",
       y = "Juvenile density (colonies/m²)") +
  theme_minimal()




```
```{r}
#extracting the coral cover of pocillopora inside the datafile 
#exract  transect name, site 
#exract  transect name, site 
data_clean <- data %>%
  mutate(
    Site = str_extract(Name, "S\\d+"),
    Transect = str_extract(Name, "T\\d+")
  )

```


```{r}
#counting the number of quadrat gir each site and transect
quadrat_count <- data_clean %>%
  distinct(Name, Site, Transect) %>%   
  group_by(Site, Transect) %>%
  summarise(n_quadrats = n(), .groups = "drop")
```

```{r}
#filter the quadrat from the wrong transect in our case, T4, T5 and T6
data_clean2 <- data_clean %>%
  filter(!(
    (Site == "S1" & Transect == "T6") |
    (Site == "S2" & Transect == "T4") |
    (Site == "S4" & Transect == "T4") |
    (Site == "S5" & Transect == "T4") |
    (Site == "S5" & Transect == "T6") |
    (is.na(Site) & Transect == "T2")
  ))

```

```{r}
#check on quadrats count after modification 
quadrat_count2 <- data_clean2 %>%
  distinct(Name, Site, Transect) %>%   
  group_by(Site, Transect) %>%
  summarise(n_quadrats = n(), .groups = "drop")

```

```{r}
#check the average of qudrats per site 
quadrat_per_site <- data_clean2 %>%
  distinct(Name, Site) %>%   
  group_by(Site) %>%
  summarise(n_quadrats = n(), .groups = "drop")

```

```{r}
#average across sites 
mean_quadrats <- mean(quadrat_per_site$n_quadrats)
min_quadrats <- min(quadrat_per_site$n_quadrats)
max_quadrats <- max(quadrat_per_site$n_quadrats)

mean_quadrats
min_quadrats
max_quadrats
```
```{r}
#check the sanity of data
# Check for NA values
na_counts <- colSums(is.na(data_clean2))
na_counts

# Bar plot of quadrats per site
ggplot(quadrat_per_site, aes(x = Site, y = n_quadrats)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Number of Quadrats per Site", x = "Site", y = "Number of Quadrats")

# Boxplot of quadrats per transect
quadrat_count2 %>%
  ggplot(aes(x = Transect, y = n_quadrats)) +
  geom_boxplot(fill = "lightgreen") +
  theme_minimal() +
  labs(title = "Quadrats Count Distribution by Transect", x = "Transect", y = "Number of Quadrats")

# Check structure of cleaned data
str(data_clean2)

# Check for duplicate entries
duplicates <- data_clean2[duplicated(data_clean2), ]
n_duplicates <- nrow(duplicates)
n_duplicates

# Check for negative counts (if applicable)
negative_counts <- data_clean2[data_clean2$n_quadrats < 0, ]
n_negative_counts <- nrow(negative_counts)
n_negative_counts
```





```{r}
#calculating the percent cover 
cover_quadrat <- data_clean2 %>%
  group_by(Name, Label.code) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(Name) %>%
  mutate(percent_cover = n / sum(n) * 100)

#add back site and transect
cover_quadrat <- cover_quadrat %>%
  left_join(
    data_clean2 %>%
      distinct(Name, Site, Transect),
    by = "Name"
  )

#check to see if each transect is at 100%
cover_quadrat %>%
  group_by(Name) %>%
  summarise(total = sum(percent_cover)) %>%
  summary()

```


```{r}
------------
  
#checking for missing categorie 
table(data_clean2$Label.code, useNA = "ifany")

#check for missing point 
data_clean2 %>%
  group_by(Site, Transect) %>%
  summarise(total_points = n())

#put everything at 100%
cover_transect2 <- data_clean2 %>%
  group_by(Site, Transect, Label.code) %>%
  summarise(n_points = n(), .groups = "drop") %>%
  group_by(Site, Transect) %>%
  mutate(percent_cover = n_points / sum(n_points) * 100) %>%
  ungroup()

#plot the graph with the 100% cver with all categorie inside 
ggplot(cover_transect2,
       aes(x = Transect,
           y = percent_cover,
           fill = Label.code)) +
  geom_bar(stat = "identity", width = 0.8) +
  facet_wrap(~ Site) +
  ylab("Relative Abundance (%)") +
  xlab("Transect") +
  theme_classic() +
  theme(
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

#add all the coral genus in one categorie call "coral"
unique(data_clean2$Label.code)

#adding a column for Coral
coral_genera <- c("Porites", "Montipora", "Tubastrea",
                  "Pocillopo", "Psammomora", "Acropora","Millepora", "Leptoseris", "Pavona","Acanthastr", "Pachyseris", "Leptastrea", "Astreopora", "Cyphastrea", "Gardinoser", "Lobophylli", "Fungia", "Sandolitha", "Montastrea", "Un coral" )  

data_clean2 <- data_clean2 %>%
  mutate(
    Benthic_group = ifelse(Label.code %in% coral_genera,
                           "Coral",
                           Label.code)
  )

#recalculating the percent cover 
cover_site_coral <- data_clean2 %>%
  group_by(Site, Benthic_group) %>%
  summarise(n_points = n(), .groups = "drop") %>%
  group_by(Site) %>%
  mutate(percent_cover = n_points / sum(n_points) * 100) %>%
  ungroup()

#organize the site for the graph 
cover_site_coral <- cover_transect_coral %>%
  mutate(Site = factor(Site, levels = c("S1", "S2", "S3", "S4", "S5", "S6", "S9", "S11", "S12", "S14", "S15", "S18")))  

#plot for the main categorie 
main_categ_cover_plot <- ggplot(cover_site_coral,
       aes(x = Site,
           y = percent_cover,
           fill = Benthic_group)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Site) +
  ylab("Relative Abundance (%)") +
  xlab("Site") +
  theme_classic()

#save the figure as jpg 
ggsave(filename = "Output/main_categ_cover_transect_plot.png",  # path to your folder
       plot = main_categ_cover_plot,
       width = 12,      # width in inches
       height = 6,      # height in inches
       dpi = 300)       # resolution


#same process but this time we just plot the coral genus relative abundance inside the transect 
#keep only the coral point
coral_only <- data_clean2 %>%
  filter(Label.code %in% coral_genera)

#calculate the genus composition for each transect
coral_site_comp <- coral_only %>%
  group_by(Site, Label.code) %>%
  summarise(n_points = n(), .groups = "drop") %>%
  group_by(Site) %>%
  mutate(percent_coral = n_points / sum(n_points) * 100) %>%
  ungroup()

#filter to only keep pocillopora data 
pocillopora_site_comp <- coral_site_comp %>%
  filter(Label.code == "Pocillopo")

#join juvenile poc density to % adult cover 
pocillopora_site_comp_combine <- left_join(density_juvenile, pocillopora_site_comp, by = "Site")

#plot with ggplot 
ggplot(pocillopora_site_comp_combine,
       aes(x = percent_coral, y = juvenile.density)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., ..p.value.label.., sep = " ~~~")),
               formula = y ~ x,
               parse = TRUE) +
  labs(x = "Adult % cover",
       y = "Juvenile density (colonies/m²)") +
  theme_minimal()




```



